/*
	title:Turkish Language Pack
	description:Servisi turkce dilinde kullanmayi saglamaktadir.Yukledikten sonra pencereyi yenilemek gerekir.
	tag:language pack
	developer:<a href="http://azer.kodfabrik.com">Azer Koculu</a>
*/
l_data = typeof l_data=='undefined'?{}:l_data;
l_data["tr"] = [
	"Evet",
	"Hayir",
	"ÇOKLU SATIR İÇİN SHIFT+KEY ANAHTARLARINI KULLANIN.",
	"ÇOKLU SATIRLARDA ; İŞARETİNİ UNUTMAYIN",
	"ÇIKTI ALMAK İÇİN echo() KOMUTUNU KULLANIN",
	"EKRANI TEMİZLEMEK İÇİN clrscr() KOMUTUNU KULLANIN",
	"Internet explorer bu sayfayı doğru görüntüleyemez, lütfen Firefox veya Opera kullanın!",
	"Kapat",
	"Adsiz Belge",
	"Kaydedilmedi",
	"Yeni döküman oluşturuldu",
	"Javascript Konsolu",
	"Önizleme",
	"Çıkmak istediğinize emin misiniz",
	"Eklentiler",
	"Arama",
	"Etiket",
	"Uygulama",
	"Yükleniyor..",
	"Yükle",
	"Kaydet",
	"Kaydet & Yükle",
	"Giriş",
	"E-Posta",
	"Parola",
	"Parola Sıfırla",
	"Kayıt Ol",
	"Yeni Parola Oluştur",
	"Üstbilgi",
	"Başlık",
	"Etiketler",
	"Boşluklarla ayırın",
	"Kaydet",
	"Erişilebilir",
	"Yayınla",
	"Yayınlamak için belgeyi kaydetmelisiniz",
	"Bağlantılar",
	"Proje adresi",
	"Belge Yöneticileri",
	"Sizin dışınızdaki (<i>Tanımladığınız e-posta adresiyle giriş yapmalılar</i>) belge yöneticilerini belirleyin.",
	"Tanımla",
	"E-Posta adreslerini boşlukla ayırın.Ör, a@mail.com b@mail.com",
	"Hesabımı Düzenle",
	"Değiştir",
	"Bul & Değiştir",
	"Ara",
	"Sonraki",
	"Değiştir",
	"Hepsini Değiştir",
	"Satıra Git",
	"Satır Numarası",
	"Git",
	"Yeni",
	"Farklı Kaydet",
	"Sil",
	"Tanıtım videosu",
	"Editör",
	"Çıkış",
	"Hesabımı Sil",
	"Sakla",
	"Terminalden aktar",
	"Çalıştır",
	"Yaklaş",
	"Uzaklaş",
	"Html editörünü kullanmak için belgeyi kaydetmelisiniz.",
	"Hata oluştu",
	"Toplam satır",
	"Yeriniz",
	"Sonuç bulunamadı",
	"Belgeler",
	"Aç",
	"Göster",
	"Kaydedilmemiş veri yok olacak, devam edilsin mi",
	"Tümü",
	"Yenile",
	"Belge Kaynağı",
	"Adres",
	"Önizleme modunu kullanmak için belgeyi kaydetmelisiniz.",
	"Seçili",
	"Açılmış",
	"belge silinecek, emin misiniz?",
	"Lütfen bekleyin",
	"Belgeyi kaydetmek için giriş yapmalısınız",
	"Başlık geçersiz karakter içeriyor",
	"Etiketler geçersiz karakter içeriyor",
	"Dosya yükleniyor, lütfen bekleyin",
	"Adres geçersiz karakter içeriyor",
	"Tüm alanları doldurmalısınız",
	"Geçersiz e-posta adresi",
	"Parola geçersiz karakter içeriyor",
	"Parolalar uyuşmuyor",
	"Bazı hatalar oluştu",
	"Hesabınız <strong>silinecek</strong>, emin misiniz",
	"Geliştirici",
	"Kullanıcı adı"
];

l_cur = "tr";
